# Site settings
author: Daisuke Hashimoto
title: tech_Otaku_Saves_The_World
header-img: img/home-bg.png
email: daisukehashimoto39@gmail.com
copyright_name: Daisuke Hashimoto
description: > # this means to ignore newlines until "baseurl:"
  The Journey of the Tech Otaku
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dice-K39

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
